create extension if not exists "pg_cron" with schema "pg_catalog";

drop extension if exists "pg_net";


  create table "public"."bible_reading" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid default auth.uid(),
    "date" date default now(),
    "book" text default ''::text,
    "chapter" integer,
    "completed" boolean default false,
    "notes" text default ''::text
      );


alter table "public"."bible_reading" enable row level security;


  create table "public"."fitness" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null default auth.uid(),
    "title" text not null,
    "type" text not null,
    "duration" bigint not null,
    "date" date not null,
    "notes" text
      );


alter table "public"."fitness" enable row level security;


  create table "public"."goals" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "title" text not null,
    "description" text,
    "target_date" date,
    "category" text not null,
    "status" text not null default 'todo'::text,
    "user_id" uuid not null default auth.uid()
      );


alter table "public"."goals" enable row level security;


  create table "public"."journal" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null default auth.uid(),
    "title" text not null,
    "body" text,
    "date" date not null
      );


alter table "public"."journal" enable row level security;


  create table "public"."monthly_summaries" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid not null,
    "month" text not null,
    "dismissed_at" timestamp with time zone default now()
      );


alter table "public"."monthly_summaries" enable row level security;


  create table "public"."prayer_log" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid not null default auth.uid(),
    "title" text not null default 'not null'::text,
    "body" text,
    "date" date not null,
    "answered" boolean not null default false
      );


alter table "public"."prayer_log" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null default gen_random_uuid(),
    "first_name" text default ''::text,
    "last_name" text default ''::text,
    "created_at" timestamp with time zone default now(),
    "email" text
      );


alter table "public"."profiles" enable row level security;


  create table "public"."verses" (
    "id" uuid not null default gen_random_uuid(),
    "reference" text not null,
    "text" text not null
      );


alter table "public"."verses" enable row level security;

CREATE UNIQUE INDEX "Users can manage their own journal entries_pkey" ON public.journal USING btree (id);

CREATE UNIQUE INDEX bible_reading_pkey ON public.bible_reading USING btree (id);

CREATE UNIQUE INDEX fitness_pkey ON public.fitness USING btree (id);

CREATE UNIQUE INDEX goals_pkey ON public.goals USING btree (id);

CREATE UNIQUE INDEX monthly_summaries_pkey ON public.monthly_summaries USING btree (id);

CREATE UNIQUE INDEX monthly_summaries_user_id_month_key ON public.monthly_summaries USING btree (user_id, month);

CREATE UNIQUE INDEX prayer_log_pkey ON public.prayer_log USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX verses_pkey ON public.verses USING btree (id);

alter table "public"."bible_reading" add constraint "bible_reading_pkey" PRIMARY KEY using index "bible_reading_pkey";

alter table "public"."fitness" add constraint "fitness_pkey" PRIMARY KEY using index "fitness_pkey";

alter table "public"."goals" add constraint "goals_pkey" PRIMARY KEY using index "goals_pkey";

alter table "public"."journal" add constraint "Users can manage their own journal entries_pkey" PRIMARY KEY using index "Users can manage their own journal entries_pkey";

alter table "public"."monthly_summaries" add constraint "monthly_summaries_pkey" PRIMARY KEY using index "monthly_summaries_pkey";

alter table "public"."prayer_log" add constraint "prayer_log_pkey" PRIMARY KEY using index "prayer_log_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."verses" add constraint "verses_pkey" PRIMARY KEY using index "verses_pkey";

alter table "public"."monthly_summaries" add constraint "monthly_summaries_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."monthly_summaries" validate constraint "monthly_summaries_user_id_fkey";

alter table "public"."monthly_summaries" add constraint "monthly_summaries_user_id_month_key" UNIQUE using index "monthly_summaries_user_id_month_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  insert into public.profiles (id, first_name, last_name)
  values (
    new.id,
    new.raw_user_meta_data->>'first_name',
    new.raw_user_meta_data->>'last_name'
  );
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$
;

grant delete on table "public"."bible_reading" to "anon";

grant insert on table "public"."bible_reading" to "anon";

grant references on table "public"."bible_reading" to "anon";

grant select on table "public"."bible_reading" to "anon";

grant trigger on table "public"."bible_reading" to "anon";

grant truncate on table "public"."bible_reading" to "anon";

grant update on table "public"."bible_reading" to "anon";

grant delete on table "public"."bible_reading" to "authenticated";

grant insert on table "public"."bible_reading" to "authenticated";

grant references on table "public"."bible_reading" to "authenticated";

grant select on table "public"."bible_reading" to "authenticated";

grant trigger on table "public"."bible_reading" to "authenticated";

grant truncate on table "public"."bible_reading" to "authenticated";

grant update on table "public"."bible_reading" to "authenticated";

grant delete on table "public"."bible_reading" to "service_role";

grant insert on table "public"."bible_reading" to "service_role";

grant references on table "public"."bible_reading" to "service_role";

grant select on table "public"."bible_reading" to "service_role";

grant trigger on table "public"."bible_reading" to "service_role";

grant truncate on table "public"."bible_reading" to "service_role";

grant update on table "public"."bible_reading" to "service_role";

grant delete on table "public"."fitness" to "anon";

grant insert on table "public"."fitness" to "anon";

grant references on table "public"."fitness" to "anon";

grant select on table "public"."fitness" to "anon";

grant trigger on table "public"."fitness" to "anon";

grant truncate on table "public"."fitness" to "anon";

grant update on table "public"."fitness" to "anon";

grant delete on table "public"."fitness" to "authenticated";

grant insert on table "public"."fitness" to "authenticated";

grant references on table "public"."fitness" to "authenticated";

grant select on table "public"."fitness" to "authenticated";

grant trigger on table "public"."fitness" to "authenticated";

grant truncate on table "public"."fitness" to "authenticated";

grant update on table "public"."fitness" to "authenticated";

grant delete on table "public"."fitness" to "service_role";

grant insert on table "public"."fitness" to "service_role";

grant references on table "public"."fitness" to "service_role";

grant select on table "public"."fitness" to "service_role";

grant trigger on table "public"."fitness" to "service_role";

grant truncate on table "public"."fitness" to "service_role";

grant update on table "public"."fitness" to "service_role";

grant delete on table "public"."goals" to "anon";

grant insert on table "public"."goals" to "anon";

grant references on table "public"."goals" to "anon";

grant select on table "public"."goals" to "anon";

grant trigger on table "public"."goals" to "anon";

grant truncate on table "public"."goals" to "anon";

grant update on table "public"."goals" to "anon";

grant delete on table "public"."goals" to "authenticated";

grant insert on table "public"."goals" to "authenticated";

grant references on table "public"."goals" to "authenticated";

grant select on table "public"."goals" to "authenticated";

grant trigger on table "public"."goals" to "authenticated";

grant truncate on table "public"."goals" to "authenticated";

grant update on table "public"."goals" to "authenticated";

grant delete on table "public"."goals" to "service_role";

grant insert on table "public"."goals" to "service_role";

grant references on table "public"."goals" to "service_role";

grant select on table "public"."goals" to "service_role";

grant trigger on table "public"."goals" to "service_role";

grant truncate on table "public"."goals" to "service_role";

grant update on table "public"."goals" to "service_role";

grant delete on table "public"."journal" to "anon";

grant insert on table "public"."journal" to "anon";

grant references on table "public"."journal" to "anon";

grant select on table "public"."journal" to "anon";

grant trigger on table "public"."journal" to "anon";

grant truncate on table "public"."journal" to "anon";

grant update on table "public"."journal" to "anon";

grant delete on table "public"."journal" to "authenticated";

grant insert on table "public"."journal" to "authenticated";

grant references on table "public"."journal" to "authenticated";

grant select on table "public"."journal" to "authenticated";

grant trigger on table "public"."journal" to "authenticated";

grant truncate on table "public"."journal" to "authenticated";

grant update on table "public"."journal" to "authenticated";

grant delete on table "public"."journal" to "service_role";

grant insert on table "public"."journal" to "service_role";

grant references on table "public"."journal" to "service_role";

grant select on table "public"."journal" to "service_role";

grant trigger on table "public"."journal" to "service_role";

grant truncate on table "public"."journal" to "service_role";

grant update on table "public"."journal" to "service_role";

grant delete on table "public"."monthly_summaries" to "anon";

grant insert on table "public"."monthly_summaries" to "anon";

grant references on table "public"."monthly_summaries" to "anon";

grant select on table "public"."monthly_summaries" to "anon";

grant trigger on table "public"."monthly_summaries" to "anon";

grant truncate on table "public"."monthly_summaries" to "anon";

grant update on table "public"."monthly_summaries" to "anon";

grant delete on table "public"."monthly_summaries" to "authenticated";

grant insert on table "public"."monthly_summaries" to "authenticated";

grant references on table "public"."monthly_summaries" to "authenticated";

grant select on table "public"."monthly_summaries" to "authenticated";

grant trigger on table "public"."monthly_summaries" to "authenticated";

grant truncate on table "public"."monthly_summaries" to "authenticated";

grant update on table "public"."monthly_summaries" to "authenticated";

grant delete on table "public"."monthly_summaries" to "service_role";

grant insert on table "public"."monthly_summaries" to "service_role";

grant references on table "public"."monthly_summaries" to "service_role";

grant select on table "public"."monthly_summaries" to "service_role";

grant trigger on table "public"."monthly_summaries" to "service_role";

grant truncate on table "public"."monthly_summaries" to "service_role";

grant update on table "public"."monthly_summaries" to "service_role";

grant delete on table "public"."prayer_log" to "anon";

grant insert on table "public"."prayer_log" to "anon";

grant references on table "public"."prayer_log" to "anon";

grant select on table "public"."prayer_log" to "anon";

grant trigger on table "public"."prayer_log" to "anon";

grant truncate on table "public"."prayer_log" to "anon";

grant update on table "public"."prayer_log" to "anon";

grant delete on table "public"."prayer_log" to "authenticated";

grant insert on table "public"."prayer_log" to "authenticated";

grant references on table "public"."prayer_log" to "authenticated";

grant select on table "public"."prayer_log" to "authenticated";

grant trigger on table "public"."prayer_log" to "authenticated";

grant truncate on table "public"."prayer_log" to "authenticated";

grant update on table "public"."prayer_log" to "authenticated";

grant delete on table "public"."prayer_log" to "service_role";

grant insert on table "public"."prayer_log" to "service_role";

grant references on table "public"."prayer_log" to "service_role";

grant select on table "public"."prayer_log" to "service_role";

grant trigger on table "public"."prayer_log" to "service_role";

grant truncate on table "public"."prayer_log" to "service_role";

grant update on table "public"."prayer_log" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."verses" to "anon";

grant insert on table "public"."verses" to "anon";

grant references on table "public"."verses" to "anon";

grant select on table "public"."verses" to "anon";

grant trigger on table "public"."verses" to "anon";

grant truncate on table "public"."verses" to "anon";

grant update on table "public"."verses" to "anon";

grant delete on table "public"."verses" to "authenticated";

grant insert on table "public"."verses" to "authenticated";

grant references on table "public"."verses" to "authenticated";

grant select on table "public"."verses" to "authenticated";

grant trigger on table "public"."verses" to "authenticated";

grant truncate on table "public"."verses" to "authenticated";

grant update on table "public"."verses" to "authenticated";

grant delete on table "public"."verses" to "service_role";

grant insert on table "public"."verses" to "service_role";

grant references on table "public"."verses" to "service_role";

grant select on table "public"."verses" to "service_role";

grant trigger on table "public"."verses" to "service_role";

grant truncate on table "public"."verses" to "service_role";

grant update on table "public"."verses" to "service_role";


  create policy "Users can delete own readings"
  on "public"."bible_reading"
  as permissive
  for delete
  to public
using ((auth.uid() = user_id));



  create policy "Users can insert own readings"
  on "public"."bible_reading"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "Users can read own readings"
  on "public"."bible_reading"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Users can only manage their own fitness entries"
  on "public"."fitness"
  as permissive
  for all
  to public
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



  create policy "Users can only manage their own goals"
  on "public"."goals"
  as permissive
  for all
  to public
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



  create policy "Users can only manage their own journal entries"
  on "public"."journal"
  as permissive
  for all
  to public
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



  create policy "Users can only insert their own summaries"
  on "public"."monthly_summaries"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "Users can only read their own summaries"
  on "public"."monthly_summaries"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Users can only manage their own prayers"
  on "public"."prayer_log"
  as permissive
  for all
  to public
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



  create policy "Users can insert own profile"
  on "public"."profiles"
  as permissive
  for insert
  to public
with check ((auth.uid() = id));



  create policy "Users can read own profile"
  on "public"."profiles"
  as permissive
  for select
  to public
using ((auth.uid() = id));



  create policy "Users can update own profile"
  on "public"."profiles"
  as permissive
  for update
  to public
using ((auth.uid() = id))
with check ((auth.uid() = id));



  create policy "Public can read verses"
  on "public"."verses"
  as permissive
  for select
  to public
using (true);


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


